# Generated by Django 5.1 on 2025-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
