# Generated by Django 5.1 on 2024-08-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
