# Generated by Django 5.0.1 on 2024-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email exist'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockmovements',
            name='actionType',
            field=models.CharField(default='Inbound', max_length=25),
        ),
        migrations.AlterField(
            model_name='warehouses',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
