# Generated by Django 5.0.1 on 2024-02-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
