# Generated by Django 4.2.27 on 2026-03-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='actionType',
            field=models.CharField(default='Inbound', max_length=30),
        ),
    ]
