# Generated by Django 5.0.1 on 2024-01-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovements',
            old_name='type',
            new_name='actionType',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='diffproducts',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filsa.warehouses'),
        ),
        migrations.AddField(
            model_name='stockmovements',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filsa.warehouses'),
        ),
        migrations.AlterField(
            model_name='diffproducts',
            name='totalPurchase',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diffproducts',
            name='totalQuantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_name', to='filsa.warehouses'),
        ),
        migrations.AlterField(
            model_name='stockmovements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stockmovements',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovements',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
