# Generated by Django 5.0.1 on 2024-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0002_rename_active_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='observations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
