# Generated by Django 4.2.27 on 2026-03-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0002_increase_actiontype_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudProductTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery Task ID')),
                ('action', models.CharField(max_length=50, verbose_name='Acción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('STARTED', 'En proceso'), ('SUCCESS', 'Completado'), ('FAILURE', 'Error')], default='PENDING', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('result_message', models.TextField(blank=True, verbose_name='Resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea CRUD Productos',
                'verbose_name_plural': 'Tareas CRUD Productos',
            },
        ),
    ]
