# Generated by Django 4.2.27 on 2026-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filsa', '0003_crud_product_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internalCode',
            field=models.BigIntegerField(unique=True, verbose_name='Codigo Interno'),
        ),
    ]
